### ISSUE TITLE
Exit scammed?

### ISSUE THREAD

**Issue by V4NSH4J** [cChimney/Discord-DM-on-Reaction#11]

**Comment by cChimney** [comment]
no?

**Comment by V4NSH4J** [comment]
why do i have people in my dms saying you sold them a gen which doesn't work and deleted telegram account 💀

**Comment by cChimney** [comment]
> why do i have people in my dms saying you sold them a gen which doesn't work and deleted telegram account 💀

sold gen to 2 people and the gen did work at the moment of me leaving the community, sold it with the promise to keep updating it till i left the community. Gen worked still after a few weeks of me deleting my account idk if it works now though as i dont have the files anymore.

**Comment by V4NSH4J** [comment]
Really? Because it looks like one person you sold it to never got it working, he kept asking you for help on it and kept getting excuses. 
<img width="530" alt="Screenshot 2022-05-01 at 8 39 28 PM" src="https://user-images.githubusercontent.com/79518089/166152114-ad30dcbf-5f63-4a85-9210-724a88d70564.png">
<img width="407" alt="Screenshot 2022-05-01 at 8 38 28 PM" src="https://user-images.githubusercontent.com/79518089/166152061-d54926aa-2e0d-4b4c-b51b-e8d93967d6b3.png">

BTW if you ask me, saying "Updates till I leave the community" then leave in 15 days, it looks like an exit scam that to with people waiting for replies from you. I Believe you'd know who it is, so please contact him.

**Comment by cChimney** [comment]
> Really? Because it looks like one person you sold it to never got it working, he kept asking you for help on it and kept getting excuses.

Gen was with phone verif but just to make shit faster the phone verify and gen were 2 diff programs, kinda his problem that it didnt work + my rdp was down for 24 hours can't remember what that had to do with anything though... Gen worked phone verifier worked too but it wasnt 100% rate unlocked which wasn't my problem as we were using anti captcha at the time which didnt give 100% rate. that was the only problem of the gen

**Comment by cChimney** [comment]
didnt mean to close, not going to contact him as i left and i don't want to come back for a little bit due to being busy with school and other things

**Comment by V4NSH4J** [comment]
In other words, exit scammed. This message of your RDP being down was your last message to him? So you left him hanging?

**Comment by cChimney** [comment]
> In other words, exit scammed. This message of your RDP being down was your last message to him? So you left him hanging with $7500 worth of software he couldn't run?

Like i said nothing was wrong with the software lol it worked flawlessly except for the rate

**Comment by V4NSH4J** [comment]
> > In other words, exit scammed. This message of your RDP being down was your last message to him? So you left him hanging with $7500 worth of software he couldn't run?
> 
> Like i said nothing was wrong with the software lol it worked flawlessly except for the rate

It worked flawlessly so you didn't reply to him and deleted account?

**Comment by cChimney** [comment]
> > > In other words, exit scammed. This message of your RDP being down was your last message to him? So you left him hanging with $7500 worth of software he couldn't run?
> > 
> > 
> > Like i said nothing was wrong with the software lol it worked flawlessly except for the rate
> 
> It worked flawlessly so you didn't reply to him and deleted account?

had lots of dms can't always remember to reply. "software" was everything he asked for though still.

**Comment by V4NSH4J** [comment]
Can't remember to reply to the guy who paid you 7.5k USD? Seems like you have your priorities set. Anyways, do you think I can get in contact with you on discord or telegram so you can explain it better? Because this looks 100% like an exit scammed that you deleted your account and "left the community" because you sold him something that didn't work.

**Comment by cChimney** [comment]
> Can't remember to reply to the guy who paid you 7.5k USD? Seems like you have your priorities set. Anyways, do you think I can get in contact with you on discord or telegram so you can explain it better? Because this looks 100% like an exit scammed that you deleted your account and "left the community" because you sold him something that didn't work.

it did work, took him time to figure it out, i helped, rate wasn't good due to anti captcha at some times couldnt do anything abt that because i didnt wanna make a solver as that wasnt included, his meaning of "doesnt work" is that the rate wasnt perfect

**Comment by V4NSH4J** [comment]
> > Can't remember to reply to the guy who paid you 7.5k USD? Seems like you have your priorities set. Anyways, do you think I can get in contact with you on discord or telegram so you can explain it better? Because this looks 100% like an exit scammed that you deleted your account and "left the community" because you sold him something that didn't work.
> 
> it did work, took him time to figure it out, i helped, rate wasn't good due to anti captcha at some times couldnt do anything abt that because i didnt wanna make a solver as that wasnt included, his meaning of "doesnt work" is that the rate wasnt perfect

How low was the rate?

**Comment by cChimney** [comment]
> > > Can't remember to reply to the guy who paid you 7.5k USD? Seems like you have your priorities set. Anyways, do you think I can get in contact with you on discord or telegram so you can explain it better? Because this looks 100% like an exit scammed that you deleted your account and "left the community" because you sold him something that didn't work.
> > 
> > 
> > it did work, took him time to figure it out, i helped, rate wasn't good due to anti captcha at some times couldnt do anything abt that because i didnt wanna make a solver as that wasnt included, his meaning of "doesnt work" is that the rate wasnt perfect
> 
> How low was the rate?

think it'd go down to 50% at times which still isn't bad as you'd make a lot of profit still

**Comment by V4NSH4J** [comment]
Did you really leave the community if you were there on an alt? We just banned you, this basically proved you deleted account just to get away from the people you sold to.

**Comment by cChimney** [comment]
Im not there on an alt though lol

**Comment by V4NSH4J** [comment]
> Im not there on an alt though lol

That's a lie ^ we basically caught you red handed lmao you coulda just said you scammed I woulda left you alone which I will do now.

**Comment by cChimney** [comment]
> > Im not there on an alt though lol
> 
> That's a lie ^ we basically caught you red handed lmao you coulda just said you scammed I woulda left you alone which I will do now.

I'd still claim that i didnt scam, person himself can contact me though if he really feels scammed...
