### ISSUE TITLE
Improper token has been passed.

### ISSUE THREAD

**Issue by San-sirwan** [cChimney/Discord-DM-on-Reaction#5]
Improper token has been passed.
anyone can say what is the error my token in correct

**Comment by cChimney** [comment]
1 - pip uninstall discord.py
2 - pip install discord.py-self httpx more-itertools
3 - listening token & message in config.json
4 - dming tokens in tokens.txt
5 - channelid:messageid in reactionChannels.txt
6 - join all tokens to the servers u wanna mass dm ;)

**Comment by cChimney** [comment]
follow those steps

**Comment by San-sirwan** [comment]
ok ty its working now!
