### ISSUE TITLE
How do i set it up

### ISSUE THREAD

**Issue by Mahg47** [cChimney/Discord-DM-on-Reaction#7]
Do I have to build it from the source? Or Can you attach the zip file here.

**Comment by Mahg47** [comment]
I'm not seeing the link to download the app here. Please, can you help direct me on how to set it up. I don't know much about this stuff.

**Comment by cChimney** [comment]
> Do I have to build it from the source? Or Can you attach the zip file here.

There's no such thing as "building" it really, u can compile it to exe but it doesnt provide any extra features so u probs should just leave it .py, u can just run it in command prompt google the shits ykyk
