### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by captaingreem** [cChimney/Discord-DM-on-Reaction#9]
can you make a captcha ressolver ?

`{'captcha_key': ['captcha-required'], 'captcha_sitekey': 'a9b5fb07-92ff-493f-86fe-352a2803b3df', 'captcha_service': 'hcaptcha', 'captcha_rqdata': '65JLcogErYLSfP5ZCz5rvXxeZtiA/JhhzvnAhZPovjaZLXudixFjvH8Gsw7IOILwo4YP9ohT/BOezA5wtk5fUotO1lGl4nTv+Eneej7ijb+ug8HkkHOjni6twl9Rn7854NtShGg0ARY4XMkYcTabzmQlnRU8coFSY7337Kxz', 'captcha_rqtoken': 'IlM2N2xyMDdrLzJCVWNzWnNNdHEwYUxnYkg2T0c2TmZZZ1BRZnFpSmhLZmpEamJ3cm5jcEtkTzcrSEJEN1BvWUsvaStGRnc9PVhUTk54R25yOU4wNHFVOTMi.YlaSjg.w_XuwCx2hoQwALRcQUPhQAH9qXA'}`

**Comment by cChimney** [comment]
If you look at the previous issue, i will not make this right now. Maybe later
